GET https://pokeapi.co/api/v2/pokemon/1

###

GET https://pokeapi.co/api/v2/pokemon/ivysaur

###
GET https://pokeapi.co/api/v2/evolution-chain/1

###
GET https://pokeapi.co/api/v2/type/12/

###
GET https://pokeapi.co/api/v2/pokemon-species/1

###
GET https://pokeapi.co/api/v2/type/15/
